### ISSUE TITLE
[API] __wakeup() method

### ISSUE THREAD

**Issue by ninjapanzer** [phalcon/incubator#842]
###### COPIED FROM https://github.com/phalcon/docs/issues/1464

PER @emiliodeg 
> There are in all exception class an __wakeup method inhereted from PHP Exception, but this don't have this method PHP Exception
Even in Phalcon sources there is no such method
Should we remove this method from all exception classes?

**Comment by sergeyklay** [comment]
@ninjapanzer Could you please explain a bit more

**Comment by emiliodeg** [comment]
Hi Sergey as you can see in all exception class i.e. [Acl_Exception](https://github.com/phalcon/docs/blob/3.2/en/api/Phalcon_Acl_Exception.md), [Annotation_Exception](https://github.com/phalcon/docs/blob/3.2/en/api/Phalcon_Annotations_Exception.md), etc all have a `__wakeup()` method inherited from [PHP Exception class](http://php.net/manual/en/class.exception.php) but this class don't have this `__wakeup()` method
The idea is remove this method from the API because doesn't exists

**Comment by sergeyklay** [comment]
@emiliodeg As you can see we just extend standard Exception class

```zep
namespace Phalcon\Acl;

class Exception extends \Phalcon\Exception
{
    // Empty class
}
```

```zep
namespace Phalcon;

class Exception extends \Exception
{
    // Empty class
}
```

There is no `__wakeup` method. Also I'm pretty sure it isn't Incubator issue. Please [use proper place for documentation related issues](https://github.com/phalcon/docs/issues). Thank you for the report, and for helping us make Phalcon better.

/cc @ninjapanzer

**Comment by emiliodeg** [comment]
I know that, the `__wakeup`  method is in API doc [ACL Exception](https://github.com/phalcon/docs/blob/3.2/en/api/Phalcon_Acl_Exception.md)

**Comment by sergeyklay** [comment]
Anyway it is not Incubator issue :)

**Comment by emiliodeg** [comment]
yeap but @ninjapanzer move it here ¯\_(ツ)_/¯
